# ──────────────────────────────────────────────────────────
# CONFIGURAÇÃO DE MONITORAMENTO DE URLs (GERADO AUTOMATICAMENTE)
#
# ATENÇÃO: Não edite este arquivo diretamente!
# Para adicionar ou remover URLs, edite o arquivo 'urls.txt'
# e execute o script: ./scripts/generate-httpcheck.sh
# ──────────────────────────────────────────────────────────

jobs:
  - name: url_apisinushubcom_api_v1_ping
    url: "https://api.sinus-hub.com/api/v1/ping"
    status_accepted:
      - 200
    timeout: 5

  - name: url_backofficesinushubcom
    url: "https://backoffice.sinus-hub.com"
    status_accepted:
      - 200
    timeout: 5

  - name: url_memberssinushubcom
    url: "https://members.sinus-hub.com"
    status_accepted:
      - 200
    timeout: 5

  - name: url_paysinushubcom
    url: "https://pay.sinus-hub.com"
    status_accepted:
      - 200
    timeout: 5

